
CREATE TABLE category (
                            category_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                            category_name varchar(50) UNIQUE
);

CREATE TABLE locations (
                             location_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                             lat float NOT NULL ,
                             lon float NOT NULL ,
                             name varchar(255)
);
CREATE TABLE users (
                       user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL ,
                       user_name varchar(50) UNIQUE NOT NULL ,
                       email varchar(200) UNIQUE NOT NULL

);

CREATE TABLE events (
                        event_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                        annotation varchar(255) NOT NULL ,
                        category_id BIGINT references category (category_id),
                        confirmedRequests INT,
                        createdOn timestamp,
                        description varchar(255) NOT NULL ,
                        eventDate timestamp,
                        initiator BIGINT references  users (user_id),
                        location BIGINT references locations (location_id),
                        paid boolean,
                        participantLimit int,
                        publishedOn timestamp,
                        requestModeration boolean,
                        state varchar(255),
                        title varchar(255)
);


CREATE TABLE participation_requests (
                                          request_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                                          created timestamp,
                                          event_id BIGINT REFERENCES events(event_id),
                                          requester BIGINT REFERENCES users(user_id),
                                          status varchar(255)
);

CREATE TABLE compilations (
                                compilation_id BIGINT PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
                                pinned boolean,
                                title varchar(255)
);

CREATE TABLE compilation_event (
                                     compilation_id BIGINT PRIMARY KEY REFERENCES compilations (compilation_id),
                                     event_id BIGINT PRIMARY KEY references events (event_id)
);