
CREATE TABLE IF NOT EXISTS hit (
    hit_id BIGINT GENERATED BY DEFAULT AS IDENITY NOT NULL,
    app VARCHAR NOT NULL,
    uri VARCHAR NOT NULL,
    ip VARCHAR NOT NULL,
    time timestamp ,
    CONSTRAINT uq_hit unique(hit_id)

);